import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { fetchAISectionInsight } from '../services/api';

const AIInsightBox = ({ sectionId, sectionTitle, chartData, onInsightStateChange }) => {
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (onInsightStateChange) {
      onInsightStateChange(!!insight);
    }
  }, [insight, onInsightStateChange]);

  const handleAskAI = async () => {
    if (loading) return;
    setLoading(true);
    setError(null);
    try {
      const payload = {
        section_id: sectionId,
        section_title: sectionTitle,
        chart_data: chartData
      };
      const response = await fetchAISectionInsight(payload);
      setInsight(response.result);
    } catch (err) {
      setError(err.message || 'Failed to fetch AI insight. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="ai-insight-container mt-4 mb-6">
      {!insight && !loading && !error && (
        <button
          onClick={handleAskAI}
          className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-medium rounded-lg shadow-md hover:from-purple-500 hover:to-indigo-500 transition-all duration-300 group print:hidden"
          title="Consult the Cosmic Oracle for a deep reading on this section"
        >
          <span className="text-xl group-hover:scale-110 transition-transform">✨</span>
          <span>Click for Deeper Insights</span>
        </button>
      )}

      {loading && (
        <div className="flex items-center gap-3 p-4 rounded-lg bg-indigo-900/30 border border-indigo-500/30">
          <div className="animate-spin h-5 w-5 border-2 border-purple-400 border-t-transparent rounded-full"></div>
          <span className="text-indigo-200 animate-pulse">Consulting the Cosmic Oracle...</span>
        </div>
      )}

      {error && (
        <div className="p-4 rounded-lg bg-red-900/30 border border-red-500/50 text-red-200">
          <p className="mb-2">⚠️ {error}</p>
          <button
            onClick={handleAskAI}
            className="text-sm underline hover:text-white"
          >
            Try Again
          </button>
        </div>
      )}

      {insight && !loading && (
        <div className="relative p-6 rounded-xl bg-gradient-to-br from-indigo-900/40 to-purple-900/40 border border-purple-500/30 shadow-lg backdrop-blur-sm mt-4 print:bg-transparent print:bg-none print:border-none print:shadow-none print:p-0">
          <div className="absolute top-0 right-0 p-3 opacity-50 text-2xl print:hidden">✨</div>
          <h4 className="text-xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-300 to-pink-300 mb-4 border-b border-purple-500/30 pb-2 flex items-center gap-2 print:text-indigo-900 print:bg-none print:border-indigo-100">
            <span>Cosmic AI Insight: {sectionTitle}</span>
          </h4>
          <div className="prose prose-invert prose-purple max-w-none 
                          prose-headings:text-black prose-headings:font-bold 
                          prose-p:text-black prose-p:leading-relaxed 
                          prose-li:text-black prose-strong:text-black
                          print:prose-p:text-gray-800 print:prose-headings:text-black print:prose-li:text-gray-800 print:prose-strong:text-black">
            <ReactMarkdown>{insight}</ReactMarkdown>
          </div>
          <div className="mt-4 pt-3 border-t border-purple-500/20 text-xs text-purple-300/60 flex justify-between items-center print:hidden">
            <span>Generated by AI Cosmic Oracle</span>
            <button onClick={() => setInsight(null)} className="hover:text-purple-200 transition-colors">Clear</button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInsightBox;
