export const WINDOW_SEQUENCE = [
  { id: 'classic_view', type: 'custom', label: 'Classic View window', url: '/?worksheet=true&fullScreen=classic_view', name: 'AstroWindow_1' },
  { id: 'lagna', type: 'worksheet', label: 'Lagna chart window', name: 'AstroWindow_2' },
  { id: 'planets_table', type: 'worksheet', label: 'Planet Position & Degree Window', name: 'AstroWindow_3' },
  { id: 'dignity', type: 'worksheet', label: 'Dignity Table Window', name: 'AstroWindow_4' },
  { id: 'sunrise_chart', type: 'custom', label: 'SunRise Chart window', url: '/?sunrise_chart=true', name: 'AstroWindow_5' },
  { id: 'd1', type: 'worksheet', label: 'D1', name: 'AstroWindow_6' },
  { id: 'd2', type: 'worksheet', label: 'D2', name: 'AstroWindow_7' },
  { id: 'd3', type: 'worksheet', label: 'D3', name: 'AstroWindow_8' },
  { id: 'd4', type: 'worksheet', label: 'D4', name: 'AstroWindow_9' },
  { id: 'd5', type: 'worksheet', label: 'D5', name: 'AstroWindow_10' },
  { id: 'd6', type: 'worksheet', label: 'D6', name: 'AstroWindow_11' },
  { id: 'd7', type: 'worksheet', label: 'D7', name: 'AstroWindow_12' },
  { id: 'd8', type: 'worksheet', label: 'D8', name: 'AstroWindow_13' },
  { id: 'd9', type: 'worksheet', label: 'D9', name: 'AstroWindow_14' },
  { id: 'd10', type: 'worksheet', label: 'D10', name: 'AstroWindow_15' },
  { id: 'd11', type: 'worksheet', label: 'D11', name: 'AstroWindow_16' },
  { id: 'd12', type: 'worksheet', label: 'D12', name: 'AstroWindow_17' },
  { id: 'd16', type: 'worksheet', label: 'D16', name: 'AstroWindow_18' },
  { id: 'd20', type: 'worksheet', label: 'D20', name: 'AstroWindow_19' },
  { id: 'd24', type: 'worksheet', label: 'D24', name: 'AstroWindow_20' },
  { id: 'd27', type: 'worksheet', label: 'D27', name: 'AstroWindow_21' },
  { id: 'd30', type: 'worksheet', label: 'D30', name: 'AstroWindow_22' },
  { id: 'd40', type: 'worksheet', label: 'D40', name: 'AstroWindow_23' },
  { id: 'd45', type: 'worksheet', label: 'D45', name: 'AstroWindow_24' },
  { id: 'd60', type: 'worksheet', label: 'D60', name: 'AstroWindow_25' },
  { id: 'vimshottari', type: 'worksheet', label: 'Vimshottari Dasha Window', name: 'AstroWindow_26' },
  { id: 'shadbala', type: 'worksheet', label: 'Shadabala Chart Window', name: 'AstroWindow_27' },
  { id: 'ashtakavarga', type: 'worksheet', label: 'Astakvarga Window', name: 'AstroWindow_28' },
  { id: 'panch_pakshi', type: 'worksheet', label: 'Panch Pakshi window', name: 'AstroWindow_29' },
  { id: 'relationships', type: 'worksheet', label: 'Relationship Window', name: 'AstroWindow_30' },
  { id: 'transit_compare', type: 'worksheet', label: 'Compare Transit Window', name: 'AstroWindow_31' },
  { id: 'solar_return', type: 'custom', label: 'Solar Return Window', url: '/?solar_return=true', name: 'AstroWindow_32' },
  { id: 'daily_solar', type: 'custom', label: 'Daily Solar Window', url: '/?daily_solar=true', name: 'AstroWindow_33' },
  { id: 'annual_varshaphala', type: 'custom', label: 'Annual Vrasphal Window', url: '/?annual_varshaphala=true', name: 'AstroWindow_34' },
  { id: 'advanced_nakshatra', type: 'custom', label: 'Advanced Nakshatra window', url: '/?advanced_nakshatra=true', name: 'AstroWindow_35' },
  { id: 'animated_transits', type: 'custom', label: 'Animated TRansit window', url: '/?animated_transits=true', name: 'AstroWindow_36' },
  { id: 'navamsha_ages', type: 'custom', label: 'Navmasa Ages Window', url: '/?navamsha_ages=true', name: 'AstroWindow_37' },
  { id: 'kp_chart', type: 'custom', label: 'KP chart Window', url: '/?kp_chart=true', name: 'AstroWindow_38' },
  { id: 'shodashottari', type: 'worksheet', label: 'Shodasotari window', name: 'AstroWindow_39' },
  { id: 'chaturshitisama', type: 'worksheet', label: 'Chaturshitisama Window', name: 'AstroWindow_40' },
  { id: 'numerical', type: 'worksheet', label: 'Numerology Window', name: 'AstroWindow_41' },
  { id: 'gemstones', type: 'worksheet', label: 'Ratna window', name: 'AstroWindow_42' },
  { id: 'transit', type: 'worksheet', label: 'Today Gochar Window', name: 'AstroWindow_43' },
  { id: 'current_positions', type: 'worksheet', label: 'Current Planet Position window', name: 'AstroWindow_44' },
  { id: 'ascendant', type: 'oracle', label: 'Ascendent Window', name: 'AstroWindow_45' },
  { id: 'study', type: 'oracle', label: 'study Window', name: 'AstroWindow_46' },
  { id: 'career', type: 'oracle', label: 'Carrer Winodw', name: 'AstroWindow_47' },
  { id: 'finance', type: 'oracle', label: 'Finance Window', name: 'AstroWindow_48' },
  { id: 'marriage', type: 'oracle', label: 'Marriage Window', name: 'AstroWindow_49' },
  { id: 'business', type: 'oracle', label: 'Business Window', name: 'AstroWindow_50' },
  { id: 'health', type: 'oracle', label: 'Health Window', name: 'AstroWindow_51' },
  { id: 'parents_health', type: 'oracle', label: 'Parents Health Window', name: 'AstroWindow_52' },
  { id: 'children_health', type: 'oracle', label: 'Childrens Health window', name: 'AstroWindow_53' },
  { id: 'mental_peace', type: 'oracle', label: 'Mental Peace Window', name: 'AstroWindow_54' },
  { id: 'home_peace', type: 'oracle', label: 'Ghar Me Shukh Shanti window', name: 'AstroWindow_55' },
  { id: 'manglik', type: 'oracle', label: 'Manglik Dosha Window', name: 'AstroWindow_56' },
  { id: 'kalsarp', type: 'oracle', label: 'Kalsarp Dosha Window', name: 'AstroWindow_57' },
  { id: 'sadesati', type: 'oracle', label: 'sadesarti Dosha Window', name: 'AstroWindow_58' },
  { id: 'rahu', type: 'oracle', label: 'Rahu dosha Window', name: 'AstroWindow_59' },
  { id: 'ketu', type: 'oracle', label: 'Ketu dosha Window', name: 'AstroWindow_60' },
  { id: 'loshu', type: 'oracle', label: 'Loshu Grid Window', name: 'AstroWindow_61' },
  { id: 'lalkitab', type: 'oracle', label: 'Lal Kitab window', name: 'AstroWindow_62' },
  { id: 'daily_panchang', type: 'oracle', label: 'Daily Panchang Window', name: 'AstroWindow_63' },
  { id: 'horary', type: 'oracle', label: 'Horary astrology Window', name: 'AstroWindow_64' },
  { id: 'chakra', type: 'oracle', label: 'Sudarshan Chakra Window', name: 'AstroWindow_65' },
  { id: 'yantra', type: 'oracle', label: 'Yantra Suggestion Window', name: 'AstroWindow_66' },
];

export const getWindowIndexById = (id) => {
  return WINDOW_SEQUENCE.findIndex(w => w.id === id);
};

export const getWindowBySerial = (serialNo) => {
  return WINDOW_SEQUENCE[serialNo - 1];
};
