import google.generativeai as genai
import os

def generate_fallback_reading(p1_name: str, p2_name: str, top_hits: list) -> str:
    """A rule-based fallback engine for when AI generation fails."""
    core_text = []
    comm_text = []
    frict_text = []
    
    for hit in top_hits:
        p1b = hit['p1_body']
        p2b = hit['p2_body']
        asp = hit['aspect_name']
        bodies = {p1b, p2b}
        
        # Core connection
        if "Sun" in bodies and "Moon" in bodies:
            if asp in ["Conjunction", "Trine", "Sextile"]:
                core_text.append(f"The {asp} between {p1_name}'s {p1b} and {p2_name}'s {p2b} creates a profound sense of familiarity and emotional alignment. You instinctively understand each other's core needs.")
            else:
                core_text.append(f"The {asp} between {p1_name}'s {p1b} and {p2_name}'s {p2b} shows an intense magnetism, though you may sometimes struggle to balance ego and emotions.")
        elif "Ascendant" in bodies:
            core_text.append(f"With an {asp} to the Ascendant, there is an immediate, noticeable physical and energetic dynamic between you.")
            
        # Communication & Affection
        if "Mercury" in bodies or "Venus" in bodies or ("Moon" in bodies and "Sun" not in bodies):
            if asp in ["Conjunction", "Trine", "Sextile"]:
                comm_text.append(f"A beautiful {asp} involving {p1b} and {p2b} suggests that your communication flows easily and affection is expressed naturally.")
            else:
                comm_text.append(f"The {asp} involving {p1b} and {p2b} means you may need to work a little harder to understand each other's love languages or communication styles, but the effort brings deep rewards.")
                
        # Friction & Growth
        if "Mars" in bodies or "Saturn" in bodies or "Rahu" in bodies or "Ketu" in bodies or asp in ["Square", "Opposition"]:
            if "Saturn" in bodies:
                frict_text.append(f"Saturn's involvement ({p1b} {asp} {p2b}) adds a serious, karmic tone. It provides 'glue' for a long-term bond, but can sometimes feel heavy or restrictive.")
            elif "Mars" in bodies:
                frict_text.append(f"The {asp} involving Mars brings a lot of heat and passion to the relationship, though it can also spark arguments if energy isn't channeled constructively.")
            elif "Rahu" in bodies or "Ketu" in bodies:
                frict_text.append(f"The Nodes (Rahu/Ketu) touching {p2b if p1b in ['Rahu','Ketu'] else p1b} indicates a fated, magnetic connection that pushes both of you to evolve.")
            else:
                frict_text.append(f"The {asp} between {p1b} and {p2b} is a point of friction, but it is precisely this tension that will help both of you grow.")

    # Remove duplicates and format
    core = " ".join(list(dict.fromkeys(core_text))) if core_text else "Your planetary alignments suggest a unique and multi-faceted connection. There is much to explore in how your energies blend."
    comm = " ".join(list(dict.fromkeys(comm_text))) if comm_text else "Communication and affection in this relationship will rely on your ongoing mutual understanding and empathy."
    frict = " ".join(list(dict.fromkeys(frict_text))) if frict_text else "You have relatively few harsh frictional aspects, which suggests a smooth, easy-going dynamic."
    
    reading = f"### 🌟 The Core Connection\n{core}\n\n"
    reading += f"### 💖 Communication & Affection\n{comm}\n\n"
    reading += f"### 🔥 Friction & Growth\n{frict}\n\n"
    reading += f"### 💫 Final Verdict\nWhile the stars offer guidance, the success of your relationship is ultimately determined by the love, patience, and conscious effort you both invest. *(Note: This reading was generated by our built-in rule engine due to network/API unavailability)*."
    
    return reading

def generate_synastry_reading(p1_name: str, p2_name: str, top_hits: list) -> str:
    """Generates an empathetic relationship reading based on geometric synastry aspects."""
    
    # Note: gemini-pro is deprecated and returns 404. Using gemini-flash-latest.
    model = genai.GenerativeModel('gemini-flash-latest')
    
    hits_text = ""
    for hit in top_hits:
        exact = "(EXACT)" if hit['is_exact'] else ""
        hits_text += f"- {p1_name}'s {hit['p1_body']} is in a {hit['aspect_name']} {exact} with {p2_name}'s {hit['p2_body']}.\n"

    prompt = f"""
    You are an expert, empathetic relationship astrologer specializing in psychological Synastry.
    I have calculated the exact geometric aspects between two people: {p1_name} and {p2_name}.

    Here are the most significant planetary connections (aspects) between their charts:
    {hits_text}

    Please write a comprehensive, beautifully formatted relationship reading analyzing these connections.
    Do NOT just list the aspects. Synthesize them into a cohesive narrative.
    
    Please structure your response with the following Markdown headings:
    ### 🌟 The Core Connection
    (Summarize the overall energetic flavor of this relationship based on the aspects).
    
    ### 💖 Communication & Affection
    (Analyze any hits involving Mercury, Venus, or the Moon).
    
    ### 🔥 Friction & Growth
    (Analyze any Squares, Oppositions, or hits involving Mars, Saturn, Rahu/Ketu).
    
    ### 💫 Final Verdict
    (A compassionate concluding thought).
    
    Keep the tone encouraging, deeply insightful, and psychologically profound. Do not use generic filler.
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"[SYNASTRY AI ERROR] {e} - Falling back to rule-based engine.")
        return generate_fallback_reading(p1_name, p2_name, top_hits)
